### ISSUE TITLE
Error executing FastaToCounts.py

### ISSUE THREAD

**Issue by jonoave** [pomo-dev/cflib#2]
Hi, I'm encountering an error trying to execute the above script.

I've previously tried to install cflib-pomo using pip, but encountered the error with scipy (which I believed you've fixed on an upload to git):
```
## installed cfllb-pomo from with pip
Traceback (most recent call last):
  File "/home/junhoe/.local/bin/FastaToCounts.py", line 13, in <module>
    import cflib.fasta as fa
  File "/home/junhoe/.local/lib/python3.6/site-packages/cflib/__init__.py", line 12, in <module>
    import cflib.main
  File "/home/junhoe/.local/lib/python3.6/site-packages/cflib/main.py", line 12, in <module>
    from scipy.misc import comb as choose
ImportError: cannot import name 'comb'
````
Thus I've installed cflib-pomo manually with:
setup.py build
setup.py install

However,now I'm encountering the following error

```
FastaToCounts.py populations.samples-raw.fa.gz pop.samples-raw.counts.gz --verbose
Traceback (most recent call last):
  File "/lustre/projects/project-junhoe/conda/envs/phylo/bin/FastaToCounts.py", line 4, in <module>
    __import__('pkg_resources').run_script('cflib-pomo==1.2.1', 'FastaToCounts.py')
  File "/lustre/projects/project-junhoe/conda/envs/phylo/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/lustre/projects/project-junhoe/conda/envs/phylo/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/lustre/projects/project-junhoe/conda/envs/phylo/lib/python3.6/site-packages/cflib_pomo-1.2.1-py3.6.egg/EGG-INFO/scripts/FastaToCounts.py", line 70, in <module>
  File "/lustre/projects/project-junhoe/conda/envs/phylo/lib/python3.6/site-packages/cflib_pomo-1.2.1-py3.6.egg/cflib/cf.py", line 308, in fasta_to_cf
TypeError: exceptions must derive from BaseException
```
Thanks in advance!

**Comment by dschrempf** [comment]
Hello,

thanks for using cflib and giving feedback!

These are actually two different problems.

1. I fixed the problem on the github repository, but did not upload a new package, that's why the pip install command still failed. I updated the package now. Installation with pip should work!

2. This was a bug in the code when throwing an error. The bug is fixed now, but you will still encounter the (now properly thrown) Value Error. It says that your sequences do not have equal length! You should fix that before going on. Please let me know if your sequences actually have equal length, because then, this is a bug in cflib!

Thanks again! Let me know if you have questions about how to use PoMo!
